/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_my_mouse_MyMouseService */

#ifndef _Included_android_my_mouse_MyMouseService
#define _Included_android_my_mouse_MyMouseService
#ifdef __cplusplus
extern "C" {
#endif
#undef android_my_mouse_MyMouseService_FIND_POTENTIAL_LEAKS
#define android_my_mouse_MyMouseService_FIND_POTENTIAL_LEAKS 0L
#undef android_my_mouse_MyMouseService_TRANSACTION_setMouseEnble
#define android_my_mouse_MyMouseService_TRANSACTION_setMouseEnble 1L
/*
 * Class:     android_my_mouse_MyMouseService
 * Method:    init_native
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_my_1mouse_MyMouseService_init_1native
  (JNIEnv *, jclass);

/*
 * Class:     android_my_mouse_MyMouseService
 * Method:    setMouseEnble_native
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_android_my_1mouse_MyMouseService_setMouseEnble_1native
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
